### ISSUE TITLE
ChannelTitleSet

### ISSUE THREAD

**Issue by angrycoding** [667bdrm/sofiactl#5]
HI, thank for reversing it. Played with it a little bit and found some weird thing. So calling ChannelTitleSet from CMS (software) - changing the title and also updates it immediately in the video stream (so the new title immediately appears on the video from the cam). Calling the same thing from you .pl script does update channel title, but nothing happens to video. So old channel title is still there. Why this can be?

**Comment by vladisslav2011** [comment]
I've encountered this bug too.
Fixed in https://github.com/vladisslav2011/sofiactl/commit/8ecc885f40648564b4366a38e38663fd34292bb0

**Comment by angrycoding** [comment]
> I've encountered this bug too.
> Fixed in [vladisslav2011@8ecc885](https://github.com/vladisslav2011/sofiactl/commit/8ecc885f40648564b4366a38e38663fd34292bb0)

Btw, your commit doesnt fix it. I found the problem myself, and the fact us that setchanneltitle is not the thing that sets channel title in the stream. Instead there exists different method where bitmask of the desired overlay should be supplied
